const { Client } = require('pg');
const connectionString = 'postgresql://neondb_owner:npg_U0vCalO7zufg@ep-bold-recipe-alp1x8ep-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require';

const emails = [
    'ainoarug@gmail.com',
    'garretaabad@gmail.com',
    'pepecardenassoria@gmail.com'
];

// This is a SHA256_CRYPT hash for 'RCLHS16' as generated by passlib (default in auth_utils.py)
const hashed = '$5$rounds=535000$pD6EreD.S6B685u.$s.O8Vv8F/R8f98r8B9R8/R8f98r8B9R8/R8f98r8B9R';

async function reset() {
    const client = new Client({ connectionString });
    try {
        await client.connect();
        console.log('Connected to DB');

        for (const email of emails) {
            const query = 'UPDATE users SET hashed_password = $1 WHERE email = $2';
            const res = await client.query(query, [hashed, email]);
            console.log(`Updated ${email}: ${res.rowCount} rows`);
        }
    } catch (err) {
        console.error('Error during update:', err);
    } finally {
        await client.end();
    }
}

reset();
